### PR TITLE
feat: send to multiple channels

### PR DESCRIPTION
**Pull request by rssnyder**
_warning: i have never written ts before, and have a beginner level understanding of js in general_

Tried my best at being able to send sales to multiple channels without making multiple API calls for the same collection.

`export DISCORD_CHANNEL_ID='879094113289519174;813159972190945322'`

Also on line 60 I tried to set the name of the NFT if it is `null`, which I have encountered. Can be removed.

If you can guide me on how you'd like this implemented, i can try and tidy it up, otherwise if it is unwanted feel free to close.

### CODE REVIEW

**Comment by darrensapalo** [comment]
It's a good initial design! I like its simplicity. Good work.

### Extending the design

If we want to extend it further, I would recommend building up some kind of interface, something like:

```
interface {
  sendMessage(details: SendMessageRequest): Promise<SendMessageResponse>
}
```

... and have a class that implements that interface for Discord, so that other messaging channels can implement it too (e.g. SMS, email, Slack, Reddit, etc).

That way, we also line it up for succeeding API contributors to add more and more channel support for the sale bot.

Coding style wise; I recommend using async-await notation, for improved readability.

**Comment by rssnyder** [comment]
@darrensapalo thanks for the feedback! I very rarely touch js/ts so I wasn't looking to put much time into this feature, just enough to stop getting rate limited and keep the notifications coming. Meaning to say I don't think I'll add much beyond what is here already.

**Comment by darrensapalo** [comment]
I see. Thanks!

**Comment by sbauch** [comment]
thanks so much for this, sorry i have been so absent - @rssnyder would be you be willing to pitch in as a maintainer? i don't really use this, but we do get quite a few inquiries about it. would really appreciate the help!

**Comment by rssnyder** [comment]
> thanks so much for this, sorry i have been so absent - @rssnyder would be you be willing to pitch in as a maintainer? i don't really use this, but we do get quite a few inquiries about it. would really appreciate the help!

Yeah I would love to clean up some of these PRs if that's ok with you, I do get a lot of use so want to pitch in. LMK if you need anything from me.

**Comment by sbauch** [comment]
added as a maintainer @rssnyder - thanks a bunch!

**Pull request merged**
